// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import {TestConfig, TestConfigData} from "./tables/TestConfig.sol";
import {ERC1155MetadataURI} from "./tables/ERC1155MetadataURI.sol";
import {ERC1155URIStorage} from "./tables/ERC1155URIStorage.sol";
import {OperatorApproval} from "./tables/OperatorApproval.sol";
import {TotalSupply, TotalSupplyData} from "./tables/TotalSupply.sol";
import {Owners} from "./tables/Owners.sol";
import {ERC1155Registry} from "./tables/ERC1155Registry.sol";
