// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/* Autogenerated file. Do not edit manually. */

import { ERC1155MetadataURI } from "./tables/ERC1155MetadataURI.sol";
import { ERC1155URIStorage } from "./tables/ERC1155URIStorage.sol";
import { OperatorApproval } from "./tables/OperatorApproval.sol";
import { TotalSupply, TotalSupplyData } from "./tables/TotalSupply.sol";
import { Owners } from "./tables/Owners.sol";
import { ERC1155Registry } from "./tables/ERC1155Registry.sol";
