// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IERC1155URIStorageSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IERC1155URIStorageSystem {
  function ERC1155__setTokenURI(uint256 tokenId, string memory tokenURI) external;

  function ERC1155__setMetadataURI(uint256 tokenId, string memory tokenURI) external;
}
